apiVersion: v1
kind: Service
metadata:
  name: quest-processing-service
spec:
  selector:
    app: quest-processing-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: LoadBalancer