apiVersion: v1
kind: Service
metadata:
  name: quest-catalog-service
spec:
  selector:
    app: quest-catalog-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer